// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPJjehWzsk7AfER9MRR3HCRgQugQwPLMQ',
    appId: '1:455616151383:web:46d01fe0bb40c269df4812',
    messagingSenderId: '455616151383',
    projectId: 'smile-kids-7005e',
    authDomain: 'smile-kids-7005e.firebaseapp.com',
    storageBucket: 'smile-kids-7005e.firebasestorage.app',
    measurementId: 'G-MMX2R2K1SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMt2AA-0HhIv5LbulGFe1xTX14l-I9mFA',
    appId: '1:455616151383:android:213d5087fa698398df4812',
    messagingSenderId: '455616151383',
    projectId: 'smile-kids-7005e',
    storageBucket: 'smile-kids-7005e.firebasestorage.app',
  );
}
